name: tomo-lecture
channels:
  - conda-forge
dependencies:
  - python ==3.7.3
  - numpy ==1.21.6
  - scipy ==1.7.3
  - Cython ==0.29.23
  - pip ==22.2.2
  - pip:
    - matplotlib ==3.5.3
    - seaborn ==0.12.0
    - PyHEADTAIL ==1.16.0
    - longitudinal_tomography ==3.4.3
    - pillow ==9.2.0
    - tqdm ==4.64.0
    - scikit-image ==0.14.2
