name: tomo-lecture
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - Cython
  - pip
  - pip:
    - matplotlib
    - seaborn
    - PyHEADTAIL ==1.16.0
    - longitudinal_tomography ==3.4.3
    - pillow
    - tqdm
    - scikit-image
